development:
  adapter: async

test:
  adapter: async

production:
  adapter: postgresql
  url: postgres://bqpjrapdfjyyll:b11ce157a070fd40b022c2e771d8d8a81fdaddb03f7d125b61dce9825c396e5e@ec2-54-243-213-188.compute-1.amazonaws.com:5432/d24l58ga4rkggf
  channel_prefix: nameofapp_production
